//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf2
{
    using System;
    using System.Collections.Generic;

    public partial class Employee
    {
        static Employee emp;
        public static Employee CreateEmployee(int ID, string Surname, string Name, string Patronymic, int TitleID)
        {
            emp = new Employee();
            emp.ID = ID;
            emp.Surname = Surname;
            emp.Name = Name;
            emp.Patronymic = Patronymic;
            emp.TitleID = TitleID;
            emp.Telephone = "Не задано";
            emp.Email = "Не задано";
            return emp;
        }
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime BirstDate { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int TitleID { get; set; }

        public virtual Title Title { get; set; }
    }
}
